### PR TITLE
[Bubble.io] -> [others]

### PR DESCRIPTION
**Pull request by TechLead-21**
# [Resource Name - Bubble]

Bubble is an drag-and-drop editor which makes design and development easy.  

Link: https://bubble.io/

#### Checklist:

- [x] I have performed a self-review of submitted resource and its follows the guidelines of the project.

### CODE REVIEW

**Comment by Alaev** [comment]
Hey @TechLead-21, Thanks for the pull request.
However, I think it's not a design resource for developers rather than an online web editor tool.

**Comment by jatin2003** [comment]
Hey @TechLead-21 I went through [Bubble](https://bubble.io/). I think It's not a Design Resource as It's used to make Website which might be useful to Non-Coders.

**Comment by bradtraversy** [comment]
Yeah, we should probably leave out website builder tools, etc.

**Comment by TechLead-21** [comment]
No worries ☺
I respect everyone's opinions

**Pull request closed without merging**
