### PR TITLE
Particles.vue3 -> Vue UI Libraries

### PR DESCRIPTION
**Pull request by robvanbakel**
# Particles.vue3

Updated dead link to documentation page for resource.

Link: [Particles.vue3](https://github.com/matteobruni/tsparticles/tree/main/components/vue3)

#### Checklist:

- [x] I have performed a self-review of submitted resource and its follows the guidelines of the project.

### CODE REVIEW

**Comment by Alaev** [comment]
Hey, @robvanbakel,

Could you please resolve the conflicts?

**Comment by robvanbakel** [comment]
I can't see or resolve any conflicts, I think that is because I deleted my fork after submitting the pull request. Should I create a new PR?

**Comment by Alaev** [comment]
@robvanbakel Yes, that would be great.

**Comment by robvanbakel** [comment]
Just created a new PR, #1048

**Pull request closed without merging**
