### PR TITLE
[React Native UI Lib] -> [React Native UI]

### PR DESCRIPTION
**Pull request by richardoey**
# React Native UI Lib

React Native UI Lib (RNUI) is a UI Toolset & Components Library for React Native from Wix

Link: https://wix.github.io/react-native-ui-lib/

#### Checklist:

- [X] I have performed a self-review of submitted resource and its follows the guidelines of the project.

### CODE REVIEW

**Review by Alaev — CHANGES_REQUESTED** [review]
Please rebase your branch on master

**Comment by richardoey** [comment]
Done. Did I do it right?

**Comment by Alaev** [comment]
@richardoey Nope, you should only have your commit in a PR

**Comment by richardoey** [comment]
> @richardoey Nope, you should only have your commit in a PR

Okay, let me try to fix this. Sorry for the incovenience

**Pull request closed without merging**
