### PR TITLE
vue ui contribution

### PR DESCRIPTION
**Pull request by akwetey**
# Resource Name - Vue UI

 Vue UI kit featuring a modern design system with dozens of custom components based on bootstrap 4.

https://designrevision.com/downloads/shards-vue/

#### Checklist:

- [x] I have performed a self-review of submitted resource and its follows the guidelines of the project.

### CODE REVIEW

**Comment by akwetey** [comment]
sorry I do not understand what you mean by unlit the file and add only the resource. Please come again and be much more clearer perhaps with an example.

**Comment by StefanSelfTaught** [comment]
@akwetey You used prettier or something like that to format the whole file. Don't do that, just add your resource.

**Comment by akwetey** [comment]
@StefanSelfTaught I added just my resource. I guessed while saving the file prettier formatted the whole thing. My bad. How do I correct that because prettier will format the whole thing once I save the file again?

**Comment by StefanSelfTaught** [comment]
@akwetey You could disable 'format on save'. If you are using VS Code you will find that in `Settings -> Extensions -> Prettier` or something like that.

**Comment by akwetey** [comment]
@StefanSelfTaught thanks very much. I will do that.

**Comment by akwetey** [comment]
@StefanSelfTaught I have disabled prettier. I hope it is better now?

**Comment by StefanSelfTaught** [comment]
Yes.

**Pull request merged**
