### PR TITLE
[Line Awesome]-> Icons Fonts

### PR DESCRIPTION
**Pull request by rogergcc**
# Line Awesome

is a free alternative for Font Awesome, flat icons that offer complete coverage of the main Font Awesome icon set. 
--

Link: https://icons8.com/line-awesome/

#### Checklist:

- [ ] I have performed a self-review of submitted resource and its follows the guidelines of the project.

### CODE REVIEW

**Comment by TagFold** [comment]
This should be in "Icon Font" category

**Comment by rogergcc** [comment]
> This should be in "Icon Font" category

Sure

**Review by rogergcc — COMMENTED** [review]
to Icon Fonts

**Comment by rogergcc** [comment]
this is repeat in Icon Fonts section.
I just realized
I don't know how change file. I going for new pull request

**Pull request merged**
