### PR TITLE
[Cruip] -> [HTML & CSS Templates]

### PR DESCRIPTION
**Pull request by pasqualevitiello**
Link: https://cruip.com/

### CODE REVIEW

**Comment by StefanSelfTaught** [comment]
Are those templates free?

**Comment by bradtraversy** [comment]
They don't seem to be free... closing

**Comment by Potenza111** [comment]
https://devdocs.io

**Comment by pasqualevitiello** [comment]
Free HTML templates available at https://cruip.com/free-templates/

**Pull request closed without merging**
