### PR TITLE
[Webflow] -> [Online Design Tools]

### PR DESCRIPTION
**Pull request by krishna7860**
# [Webflow]

Break the code barrier
Build better business websites, faster. Without coding.

Link: https://webflow.com/

#### Checklist:

- [x] I have performed a self-review of submitted resource and its follows the guidelines of the project.

### CODE REVIEW

**Comment by Alaev** [comment]
Hey, from what I can see its an online web editor tool and not much as design recourse for developers.

**Comment by krishna7860** [comment]
This website is a great resource for templates and good static designs as well it allows us to edit them

**Comment by StefanSelfTaught** [comment]
It seems ok for me, comparing to the other resources in the [Online Design Tools] section.

**Comment by bradtraversy** [comment]
I don't know about website building tools like Wix, webflow, etc. I'll add this one but I don't think we should include a bunch of these drag and drop builders

**Comment by krishna7860** [comment]
One thing I need to say, this way my message can reach you @bradtraversy 
I am very thankful to you Brad, your courses helped me building my blocks and I successfully placed in a startup in this quarantine time all because of your guidance world best mentor you are

**Pull request merged**
