### PR TITLE
[Mohamed achraf] -> [Logos]

### PR DESCRIPTION
**Pull request by mouadTaoussi**
# Mohamed Achraf

Added Mohamed Achraf's channel that teaches how to make basic logos, for developers to make their own custom logos.

Link: https://www.youtube.com/c/MohamedAchraf/videos

#### Checklist:

- [x]  I have performed a self-review of submitted resource and its follows the guidelines of the project.

### CODE REVIEW

**Comment by Alaev** [comment]
Closing

Not a design resource, this list is for resource and not tutorials.

Thanks

**Comment by Alaev** [comment]
Cool chanel by the way.

**Comment by mouadTaoussi** [comment]
You gave me the motivation to add another Pull requests due to the instant response to them, it's my first PR by the way.

**Comment by mouadTaoussi** [comment]
I can add new section and add initial resources to it ?  
Section: Charts Libraries

**Pull request closed without merging**
