### PR TITLE
[added Pixalabay ]-[Stock video]

### PR DESCRIPTION
**Pull request by Mhassanbughio**
**Please delete this line before submitting**, _Pull request TITLE should look like this_: `[Resource] -> [Resource Section In Docs]`

# Resource Name - [added Pixalabay ]-[Stock video]

#Edit this line with Small Description about new added resource (It has same Stock and video ) 

Link: www.linkToResource

#### Checklist:

- [ Y] I have performed a self-review of submitted resource and its follows the guidelines of the project.

### CODE REVIEW

**Comment by StefanSelfTaught** [comment]
It's called Pixabay and could you take a look at the resource above your link please 😄 ?

**Comment by Alaev** [comment]
Closed

**Comment by StefanSelfTaught** [comment]
Noooo let him close it.

**Comment by Mhassanbughio** [comment]
Closed.

**Pull request closed without merging**
