### PR TITLE
[Get BEM] -> [Design Systems & Style Guides]

### PR DESCRIPTION
**Pull request by genesisgabiola**
# Get BEM

Block Element Modifier is a methodology that helps you to create reusable components and code sharing in front-end development

Link: http://getbem.com/

#### Checklist:

- [x] I have performed a self-review of submitted resource and its follows the guidelines of the project.

### CODE REVIEW

**Comment by Alaev** [comment]
to be honest, BEM is not a design resource. Closing.

**Comment by genesisgabiola** [comment]
> to be honest, BEM is not a design resource. Closing.

but it's a style guide, right? since it makes writing CSS better which is used to design a page.
Please enlighten me about this, thank you.

**Comment by Alaev** [comment]
If we start adding terminology then we would have to add smacss, atomic css, oocss and etc... from there we would go into atomic design methodology. BEM is a flavor and not a design resource. To be honest this days with css in js you don't need it.

If you like you can add new section for this kind of resources that will cover different ways of structuring CSS listed above.

**Comment by genesisgabiola** [comment]
@Alaev thanks for clearing it out for me, btw I added #642 for a new resource as you suggested.

**Pull request closed without merging**
